version: '3.9'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    container_name: spring_db
    networks:
      - learn_spring_net
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASS
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot
    restart: on-failure
    networks:
      - learn_spring_net
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .:/app

volumes:
  db:

networks:
  learn_spring_net:
    name: learn_spring_net
    driver: bridge
