version: '3.9'
services:
  mysqldb:
    images: mysql:latest
    restart: unless-stopped
    networks:
      - learn_spring_net
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: spring_boot:19
    restart: on-failure
    networks:
      - learn_spring_net
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .:/app

volumes:
  db:

networks:
  learn_spring_net:
